language: shell
sudo: required
services: 
  - docker
env:
  - distribution: centos
    version: '7'
  - distribution: centos
    version: '8'
  - distribution: ubuntu
    version: xenial
  - distribution: ubuntu
    version: bionic
  - distribution: debian
    version: stretch
  - distribution: debian
    version: jessie


before_install:
  - sudo chmod +x daemon-config.sh
  - sudo ./daemon-config.sh
  - sudo cat /etc/docker/daemon.json
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}:${version} --tag=${distribution}-${version}:shellscript travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/Wordpress-LEMP:rw ${distribution}-${version}:shellscript > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env TERM=xterm bash startup.sh'
  - 'sudo docker rm -f "$(cat ${container_id})"'
