version: '3'

volumes:
        wordpress:
        db:

services:
        wordpress:
                image: wordpress:5.7.1-fpm-alpine
                restart: always
                container_name: ${WP_CONTAINER_NAME}
                hostname: ${WP_HOSTNAME}
                environment:
                        WORDPRESS_DB_HOST: ${DATABASE_HOSTNAME}:3306
                        WORDPRESS_DB_USER: ${DATABASE_USERNAME}
                        WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
                        WORDPRESS_DB_NAME: ${DATABASE_TABLE}
                        WORDPRESS_TABLE_PREFIX: wp_
                        WORDPRESS_DEBUG: 1
                volumes:
                        - wordpress:/var/www/html
                        - ./wordpress/wp-config/my-wp-config-docker.php:/var/www/html/wp-config.php
                        - ./wordpress/php-fpm/my-php-development.ini:/usr/local/etc/php/php.ini
                depends_on:
                        - db
                ports:
                        - 9000:9000

        db:
                image: mysql:5.7
                restart: always
                hostname: ${DATABASE_HOSTNAME}
                container_name: ${DATABASE_CONTAINER_NAME}
                environment:
                        MYSQL_DATABASE: ${DATABASE_TABLE}
                        MYSQL_USER: ${DATABASE_USERNAME}
                        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
                        MYSQL_RANDOM_ROOT_PASSWORD: '1'
                volumes:
                        - db:/var/lib/mysql
                ports:
                        - 3306:3306
        web:
                image: nginx:1.19.10-alpine
                hostname: ${WEB_HOSTNAME}
                container_name: ${WEB_CONTAINER_NAME}
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - wordpress:/var/www/html
                        - ./nginx/my-nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/my-default.conf:/etc/nginx/conf.d/wordpress.conf
                        - ./nginx/ssl:/etc/nginx/certs/
                depends_on:
                        - db
                        - wordpress
                command: apk add certbot certbot-nginx && cd /etc/nginx/certs && certbot --nginx -d ${WEB_DOMAIN} -d www.${WEB_DOMAIN} && nginx -g "daemon off;"
networks:
        default:
                external:
                        name: ${NETWORK}
