version: '3'

volumes:
        wordpress:
        db:

services:
        wordpress:
                build: ./wordpress
                image: wp:custom
                restart: always
                container_name: ${WP_CONTAINER_NAME}
                hostname: ${WP_HOSTNAME}
                volumes:
                        - wordpress:/var/www/html:rw
                        - ./wordpress/wp-content:/var/www/html/wp-content 
                environment:
                        WORDPRESS_DB_HOST: ${DATABASE_HOSTNAME}:3306
                        WORDPRESS_DB_USER: ${DATABASE_USERNAME}
                        WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
                        WORDPRESS_DB_NAME: ${DATABASE_TABLE}

                depends_on:
                        - db
                        - php

        php:
                build: ./php
                image: php:custom
                restart: always
                container_name: ${PHP_CONTAINER_NAME}
                hostname: ${PHP_HOSTNAME}
                volumes:
                        - ./php/php.ini:/usr/local/etc/php/php.ini
                ports:
                        - 9000:9000
                volumes:
                        - wordpress:/var/www/html


        db:
                image: mysql:5.7
                restart: always
                hostname: ${DATABASE_HOSTNAME}
                container_name: ${DATABASE_CONTAINER_NAME}
                environment:
                        MYSQL_DATABASE: ${DATABASE_TABLE}
                        MYSQL_USER: ${DATABASE_USERNAME}
                        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
                        MYSQL_RANDOM_ROOT_PASSWORD: '1'
                volumes:
                        - db:/var/lib/mysql
                ports:
                        - 3306:3306
        web:
                image: nginx:1.19.10-alpine
                hostname: ${WEB_HOSTNAME}
                container_name: ${WEB_CONTAINER_NAME}
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - wordpress:/var/www/html:rw
                          #- ./wordpress/wp-config/functions.php:/var/www/html/wp-includes/functions.php:rw
                        - ./nginx/my-nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/my-default.conf:/etc/nginx/conf.d/wordpress.conf
                        - ./nginx/ssl:/etc/nginx/certs/
                depends_on:
                        - db
                        - wordpress
networks:
        default:
                external:
                        name: ${NETWORK}