FROM ubuntu:bionic

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y sudo curl openssl software-properties-common systemd && rm -rf /var/lib/apt/lists/* 
WORKDIR /Wordpress-LEMP
ENTRYPOINT ["/bin/systemd"]
