FROM ubuntu:xenial

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y sudo curl openssl software-properties-common && rm -rf /var/lib/apt/lists/*
WORKDIR /Wordpress-LEMP
ENTRYPOINT ["/sbin/init"]
