name: Github-Action
on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        distribution: ["centos:7", "centos:8", "ubuntu:bionic", "ubuntu:xenial", "debian:jessie", "debian:stretch", "archlinux:latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Building Linux Environment
      run: |
        chmod +x daemon-config.sh
        ./daemon-config.sh
        docker pull ${{ matrix.distribution }}
        docker build . --tag=${{ matrix.distribution }} --file=./docker/Dockerfile.${{ matrix.distribution }} --no-cache --rm 
      shell: bash

    - name: Running Script on Linux Environment
      run: |
        container_id=$(mktemp)
        docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v ${PWD}:/Wordpress-LEMP:rw ${{ matrix.distribution }} > "${container_id}"
        docker exec "$(cat ${container_id})" env TERM=xterm bash startup.sh
        docker rm -f "$(cat ${container_id})"
      shell: bash

