name: Testing script for each Linux environment

on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        distribution: ["centos:7", "centos:8", "ubuntu:bionic", "ubuntu:xenial", "debian:jessie", "debian:stretch"]
    steps:
    - uses: actions/checkout@v2
    - name: Installing Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        DRY_RUN=1 sh ./get-docker.sh
    - name: Starting Test Build Environment
      run: |
        chmod +x daemon-config.sh
        ./daemon-config.sh
        docker pull ${{ matrix.distribution }}
        ls -al ./travis/Dockerfile.${{ matrix.distribution }}
        docker build . --tag=${{ matrix.distribution }} --file=./travis/Dockerfile.${{ matrix.distribution }} --no-cache --rm 
      shell: bash

    - name: Building Test
      run: |
        container_id=$(mktemp)
        docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v ${PWD}:/Wordpress-LEMP:rw ${{ matrix.distribution }} > "${container_id}"
        #'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro "${image_id}" > "${container_id}"'
        docker exec "$(cat ${container_id})" env TERM=xterm bash startup.sh
        docker rm -f "$(cat ${container_id})"
      shell: bash

